### ISSUE TITLE
Latest 0.5.0 causes etree.so errors

### ISSUE THREAD

**Issue by avxkim** [tilmanginzel/alfred-bluetooth-workflow#11] opened 2019-10-08 07:27 UTC
When using an older version, i have no issues under Catalina, but 0.5.0 gives such error about `etree.so` from unidentified developer.

I also have this issue with airpods: https://github.com/tilmanginzel/alfred-bluetooth-workflow/issues/10

**Comment by tilmanginzel** [comment] 2019-10-08 17:36
Hi, #10 was just fixed. :) Will close this as duplicate of #9 and comment there regarding Catalina.

**Closed as completed by tilmanginzel** 2019-10-08 17:36 UTC
